spring:
  datasource:
    url: jdbc:h2:mem:library
  sql:
    init:
      mode: always
      schema-locations: schema.sql
      data-locations: data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: false
    show-sql: false