spring:
  datasource:
    url: jdbc:h2:mem:library
    initialization-mode: always
    schema: schema.sql
    data: data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true
    show-sql: true