spring:
  data:
    #TODO configure
    mongodb:
      database: library
      authentication-database:
      username:
      password:
      host: localhost
      port:

mongock:
  change-logs-scan-package: ru.otus.erinary.hw08.library.dao.changelog
  runner-type: initializingbean

