spring:
  data:
    #TODO configure
    mongodb:
      database: library
      host: localhost
      port: 27017

mongock:
  change-logs-scan-package: ru.otus.erinary.hw08.library.dao.changelog
  runner-type: initializingbean

