spring:
  datasource:
    url: jdbc:h2:mem:library
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: false
    show-sql: false

server:
  error:
    include-stacktrace: always