spring:
  data:
    mongodb:
      database: library
      host: localhost
      port: 27017

mongock:
  change-logs-scan-package: ru.otus.erinary.hw11.library.dao.changelog
  runner-type: initializingbean

server:
  error:
    include-stacktrace: always
  port: 8085